# SOURCE
LINK_TRACKING_SOURCE = 'LINK_TRACKING'
TWO_PANE_SOURCE = 'TWO_PANE'
COOKIE_SOURCE = 'COOKIE'
COOKIELESS_SOURCE = 'COOKIELESS'
CLIENT_S2S_SOURCE = 'CLIENT_S2S'

# SOURCE_TYPE
CLICKMETER_SOURCE_TYPE = 'CLICKMETER'

# ENABLED SOURCES
CLICKMTER_CLICK_SOURCE_LIST = [LINK_TRACKING_SOURCE, TWO_PANE_SOURCE]
CLICKMETER_CONVERSION_SOURCE_LIST = [COOKIE_SOURCE, COOKIELESS_SOURCE, CLIENT_S2S_SOURCE]
CLICKMETER_ENABLED_SOURCE_LIST = [LINK_TRACKING_SOURCE, TWO_PANE_SOURCE, COOKIE_SOURCE, COOKIELESS_SOURCE, CLIENT_S2S_SOURCE]

# INGEST FROM CSV MANDATORY COLUMNS
MANDATORY_COLUMNS = ['DATE', 'REF_NUMBER', 'IP', 'USER_AGENT', 'USER_FP', 'URL', 'SOURCE']

# KAFKA TOPICS
CLICKMETER_CLICK_KAFKA_TOPIC = 'trk-ring-fp'
CLICKMETER_CONVERSION_KAFKA_TOPIC = 'trk-cookieless-fp'
